
// FILE GENERATED BY generate-api-bindings.py

#ifdef __EMSCRIPTEN__
#ifndef NAPI_BINDINGS

#include <array>
#include <emscripten/bind.h>
#include <ode/utils.h>
#include "renderer-api.h"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(ode) {

    constant("PIXEL_FORMAT_RGBA", ODE_PIXEL_FORMAT_RGBA);
    constant("PIXEL_FORMAT_PREMULTIPLIED_RGBA", ODE_PIXEL_FORMAT_PREMULTIPLIED_RGBA);

    class_<ODE_Bitmap>("Bitmap").constructor<>()
        .property("format", &ODE_Bitmap::format)
        .property("pixels", &ODE_Bitmap::pixels)
        .property("width", &ODE_Bitmap::width)
        .property("height", &ODE_Bitmap::height);

    value_object<ODE_BitmapRef>("BitmapRef")
        .field("format", &ODE_BitmapRef::format)
        .field("pixels", &ODE_BitmapRef::pixels)
        .field("width", &ODE_BitmapRef::width)
        .field("height", &ODE_BitmapRef::height);

    class_<ODE_PR1_FrameView>("PR1_FrameView").constructor<>()
        .property("width", &ODE_PR1_FrameView::width)
        .property("height", &ODE_PR1_FrameView::height)
        .property("offset", &ODE_PR1_FrameView::offset)
        .property("scale", &ODE_PR1_FrameView::scale);

    class_<ODE_RendererContextHandle>("RendererContextHandle").constructor<>();
    class_<ODE_DesignImageBaseHandle>("DesignImageBaseHandle").constructor<>();
    class_<ODE_PR1_AnimationRendererHandle>("PR1_AnimationRendererHandle").constructor<>();

    function("destroyBitmap", &ode_destroyBitmap, allow_raw_pointers());
    function("createRendererContext", &ode_createRendererContext, allow_raw_pointers());
    function("destroyRendererContext", &ode_destroyRendererContext, allow_raw_pointers());
    function("createDesignImageBase", &ode_createDesignImageBase, allow_raw_pointers());
    function("destroyDesignImageBase", &ode_destroyDesignImageBase, allow_raw_pointers());
    function("design_loadImagePixels", &ode_design_loadImagePixels, allow_raw_pointers());
    function("pr1_drawComponent", &ode_pr1_drawComponent, allow_raw_pointers());
    function("pr1_createAnimationRenderer", &ode_pr1_createAnimationRenderer, allow_raw_pointers());
    function("pr1_destroyAnimationRenderer", &ode_pr1_destroyAnimationRenderer, allow_raw_pointers());
    function("pr1_animation_drawFrame", &ode_pr1_animation_drawFrame, allow_raw_pointers());

}

#endif // NAPI_BINDINGS
#endif // __EMSCRIPTEN__
