
// Generated by json-cpp-gen by Viktor Chlumsky
// https://github.com/Chlumsky/json-cpp-gen

#pragma once

#include <nonstd/serialize_float.hpp>
#include <octopus/general.h>
#include "DocumentAnimation.h"

namespace ode {

class AnimationSerializer {

public:
    struct Error {
        enum Type {
            OK,
            UNREPRESENTABLE_FLOAT_VALUE,
            UNKNOWN_ENUM_VALUE
        } type;
        const void *datapoint;

        inline Error(Type type = Error::OK) : type(type), datapoint() { }
        inline Error(Type type, const void *datapoint) : type(type), datapoint(datapoint) { }
        operator Type() const;
        operator bool() const;
        const char *typeString() const;
    };

    static Error serialize(std::string &jsonString, const ode::DocumentAnimation &input);

protected:
    std::string &json;

    AnimationSerializer(std::string &json);
    void writeEscaped(char c);

    Error serializeStdString(const std::string &value);
    Error serializeOdeLayerAnimationType(const ode::LayerAnimation::Type &value);
    Error serializeDouble(const double &value);
    Error serializeStdVectorDouble(const std::vector<double> &value);
    Error serializeStdArrayDouble6(const std::array<double, 6> &value);
    Error serializeOctopusColor(const octopus::Color &value);
    Error serializeOdeLayerAnimationKeyframe(const ode::LayerAnimation::Keyframe &value);
    Error serializeStdVectorOdeLayerAnimationKeyframe(const std::vector<ode::LayerAnimation::Keyframe> &value);
    Error serializeStdArrayDouble2(const std::array<double, 2> &value);
    Error serializeOdeLayerAnimation(const ode::LayerAnimation &value);
    Error serializeStdVectorOdeLayerAnimation(const std::vector<ode::LayerAnimation> &value);
    Error serializeOdeDocumentAnimation(const ode::DocumentAnimation &value);

};

}
