
#include <cstdlib>
#include <cstdio>
#include "AnimationParser.h"

// Generated by json-cpp-gen by Viktor Chlumsky
// https://github.com/Chlumsky/json-cpp-gen

namespace ode {

AnimationParser::Error::operator AnimationParser::ErrorType() const {
    return type;
}

AnimationParser::Error::operator bool() const {
    return type != ErrorType::OK;
}

const char *AnimationParser::Error::typeString() const {
    switch (type) {
        case ErrorType::OK:
            return "OK";
        case ErrorType::JSON_SYNTAX_ERROR:
            return "JSON_SYNTAX_ERROR";
        case ErrorType::UNEXPECTED_END_OF_FILE:
            return "UNEXPECTED_END_OF_FILE";
        case ErrorType::TYPE_MISMATCH:
            return "TYPE_MISMATCH";
        case ErrorType::ARRAY_SIZE_MISMATCH:
            return "ARRAY_SIZE_MISMATCH";
        case ErrorType::UNKNOWN_KEY:
            return "UNKNOWN_KEY";
        case ErrorType::UNKNOWN_ENUM_VALUE:
            return "UNKNOWN_ENUM_VALUE";
        case ErrorType::VALUE_OUT_OF_RANGE:
            return "VALUE_OUT_OF_RANGE";
        case ErrorType::STRING_EXPECTED:
            return "STRING_EXPECTED";
        case ErrorType::UTF16_ENCODING_ERROR:
            return "UTF16_ENCODING_ERROR";
    }
    return "";
}

AnimationParser::AnimationParser(const char *str) : cur(str) { }

void AnimationParser::skipWhitespace() {
    while (*cur == ' ' || *cur == '\t' || *cur == '\r' || *cur == '\n')
        ++cur;
}

AnimationParser::ErrorType AnimationParser::skipValue() {
    int openBrackets = 1;
    skipWhitespace();
    switch (*cur) {
        case '\0':
            return ErrorType::UNEXPECTED_END_OF_FILE;
        case '"':
            while (*++cur != '"') {
                if (!*(cur += *cur == '\\'))
                    return ErrorType::UNEXPECTED_END_OF_FILE;
            }
            ++cur;
            return ErrorType::OK;
        case '[': case '{':
            while (openBrackets) {
                switch (*++cur) {
                    case '\0':
                        return ErrorType::UNEXPECTED_END_OF_FILE;
                    case '"':
                        if (ErrorType error = skipValue())
                            return error;
                        break;
                    case '[': case '{':
                        ++openBrackets;
                        break;
                    case ']': case '}':
                        --openBrackets;
                        break;
                }
            }
            ++cur;
            return ErrorType::OK;
        default:
            if (isAlphanumeric(*cur) || *cur == '-' || *cur == '.') {
                while (isAlphanumeric(*++cur) || *cur == '+' || *cur == '-' || *cur == '.');
                return ErrorType::OK;
            }
    }
    return ErrorType::JSON_SYNTAX_ERROR;
}

bool AnimationParser::matchSymbol(char s) {
    skipWhitespace();
    if (*cur == s) {
        ++cur;
        return true;
    }
    return false;
}

AnimationParser::ErrorType AnimationParser::unescape(char *codepoints) {
    switch (*++cur) {
        case '\0':
            return ErrorType::UNEXPECTED_END_OF_FILE;
        case 'B': case 'b': codepoints[0] = '\b'; break;
        case 'F': case 'f': codepoints[0] = '\f'; break;
        case 'N': case 'n': codepoints[0] = '\n'; break;
        case 'R': case 'r': codepoints[0] = '\r'; break;
        case 'T': case 't': codepoints[0] = '\t'; break;
        case 'U': case 'u': {
            unsigned long cp;
            unsigned short wc;
            ++cur;
            if (!(cur[0] && cur[1] && cur[2] && cur[3]))
                return ErrorType::JSON_SYNTAX_ERROR;
            codepoints[0] = cur[0], codepoints[1] = cur[1], codepoints[2] = cur[2], codepoints[3] = cur[3];
            codepoints[4] = '\0';
            cur += 3;
            if (sscanf(codepoints, "%hx", &wc) != 1)
                return ErrorType::JSON_SYNTAX_ERROR;
            if ((wc&0xfc00) == 0xd800) {
                if (!(cur[1] == '\\' && (cur[2] == 'u' || cur[2] == 'U')))
                    return ErrorType::UTF16_ENCODING_ERROR;
                cp = (unsigned long) (wc&0x03ff)<<10;
                cur += 3;
                if (!(cur[0] && cur[1] && cur[2] && cur[3]))
                    return ErrorType::JSON_SYNTAX_ERROR;
                codepoints[0] = cur[0], codepoints[1] = cur[1], codepoints[2] = cur[2], codepoints[3] = cur[3];
                codepoints[4] = '\0';
                cur += 3;
                if (sscanf(codepoints, "%hx", &wc) != 1)
                    return ErrorType::JSON_SYNTAX_ERROR;
                if ((wc&0xfc00) != 0xdc00)
                    return ErrorType::UTF16_ENCODING_ERROR;
                cp = 0x010000+(cp|(unsigned long) (wc&0x03ff));
            } else
                cp = wc;
            if (cp&0xffffff80) {
                int len;
                for (len = 1; cp>>(5*len+1) && len < 6; ++len);
                codepoints[0] = (char) (0xff<<(8-len)|cp>>6*(len-1));
                for (int i = 1; i < len; ++i)
                    *++codepoints = (char) (0x80|(cp>>6*(len-i-1)&0x3f));
            } else
                codepoints[0] = (char) cp;
            break;
        }
        default:
            codepoints[0] = *cur;
    }
    codepoints[1] = '\0';
    return ErrorType::OK;
}

bool AnimationParser::isAlphanumeric(char c) {
    switch (c) {
        case 'A': case 'B': case 'C': case 'D': case 'E': case 'F': case 'G': case 'H': case 'I':
        case 'J': case 'K': case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q': case 'R':
        case 'S': case 'T': case 'U': case 'V': case 'W': case 'X': case 'Y': case 'Z':
        case 'a': case 'b': case 'c': case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
        case 'j': case 'k': case 'l': case 'm': case 'n': case 'o': case 'p': case 'q': case 'r':
        case 's': case 't': case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
        case '0': case '1': case '2': case '3': case '4': case '5': case '6': case '7': case '8': case '9':
            return true;
        default:
            return false;
    }
}

AnimationParser::Error AnimationParser::parse(ode::DocumentAnimation &output, const char *jsonString) {
    AnimationParser parser(jsonString);
    ErrorType error = parser.parseOdeDocumentAnimation(output);
    return Error(error, static_cast<int>(parser.cur-jsonString));
}

AnimationParser::ErrorType AnimationParser::parseStdString(std::string &value) {
    skipWhitespace();
    if (*cur != '"')
        return ErrorType::STRING_EXPECTED;
    value.clear();
    while (*++cur != '"') {
        if (*cur == '\\') {
            char buffer[8];
            if (Error error = unescape(buffer))
                return error;
            value += buffer;
            continue;
        }
        if (!*cur)
            return ErrorType::UNEXPECTED_END_OF_FILE;
        value.push_back(*cur);
    }
    ++cur;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseOdeLayerAnimationType(ode::LayerAnimation::Type &value) {
    std::string str;
    if (ErrorType error = parseStdString(str))
        return error;
    if (str == "TRANSFORM")
        value = ode::LayerAnimation::Type::TRANSFORM;
    else if (str == "ROTATION")
        value = ode::LayerAnimation::Type::ROTATION;
    else if (str == "OPACITY")
        value = ode::LayerAnimation::Type::OPACITY;
    else if (str == "FILL_COLOR")
        value = ode::LayerAnimation::Type::FILL_COLOR;
    else
        return ErrorType::UNKNOWN_ENUM_VALUE;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseDouble(double &value) {
    char *end;
    value = strtod(cur, &end);
    if (end == cur)
        return ErrorType::TYPE_MISMATCH;
    cur = end;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseStdVectorDouble(std::vector<double> &value) {
    if (!matchSymbol('['))
        return ErrorType::TYPE_MISMATCH;
    value.clear();
    int separatorCheck = -1;
    while (!matchSymbol(']')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseDouble((value.emplace_back(), value.back())))
            return error;
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseNonstdOptionalStdVectorDouble(nonstd::optional<std::vector<double> > &value) {
    skipWhitespace();
    if (cur[0] == 'n' && cur[1] == 'u' && cur[2] == 'l' && cur[3] == 'l' && !isAlphanumeric(cur[4]) && cur[4] != '_' && ((cur += 4), true))
        value.reset();
    else if (Error error = parseStdVectorDouble((value = std::vector<double>()).value()))
        return error;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseStdArrayDouble6(std::array<double, 6> &value) {
    if (!matchSymbol('['))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    int i = 0;
    while (!matchSymbol(']')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (i == 6)
            return ErrorType::ARRAY_SIZE_MISMATCH;
        if (ErrorType error = parseDouble(value[i]))
            return error;
        ++i;
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    if (i != 6)
        return ErrorType::ARRAY_SIZE_MISMATCH;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseNonstdOptionalStdArrayDouble6(nonstd::optional<std::array<double, 6> > &value) {
    skipWhitespace();
    if (cur[0] == 'n' && cur[1] == 'u' && cur[2] == 'l' && cur[3] == 'l' && !isAlphanumeric(cur[4]) && cur[4] != '_' && ((cur += 4), true))
        value.reset();
    else if (Error error = parseStdArrayDouble6((value = std::array<double, 6>()).value()))
        return error;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseNonstdOptionalDouble(nonstd::optional<double> &value) {
    skipWhitespace();
    if (cur[0] == 'n' && cur[1] == 'u' && cur[2] == 'l' && cur[3] == 'l' && !isAlphanumeric(cur[4]) && cur[4] != '_' && ((cur += 4), true))
        value.reset();
    else if (Error error = parseDouble((value = double()).value()))
        return error;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseOctopusColor(octopus::Color &value) {
    std::string key;
    if (!matchSymbol('{'))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    while (!matchSymbol('}')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseStdString(key))
            return error;
        if (!matchSymbol(':'))
            return ErrorType::JSON_SYNTAX_ERROR;
        if (key == "r") {
            if (Error error = parseDouble(value.r))
                return error;
        } else if (key == "g") {
            if (Error error = parseDouble(value.g))
                return error;
        } else if (key == "b") {
            if (Error error = parseDouble(value.b))
                return error;
        } else if (key == "a") {
            if (Error error = parseDouble(value.a))
                return error;
        } else {
            if (Error error = skipValue())
                return error;
        }
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseNonstdOptionalOctopusColor(nonstd::optional<octopus::Color> &value) {
    skipWhitespace();
    if (cur[0] == 'n' && cur[1] == 'u' && cur[2] == 'l' && cur[3] == 'l' && !isAlphanumeric(cur[4]) && cur[4] != '_' && ((cur += 4), true))
        value.reset();
    else if (Error error = parseOctopusColor((value = octopus::Color()).value()))
        return error;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseOdeLayerAnimationKeyframe(ode::LayerAnimation::Keyframe &value) {
    std::string key;
    if (!matchSymbol('{'))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    while (!matchSymbol('}')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseStdString(key))
            return error;
        if (!matchSymbol(':'))
            return ErrorType::JSON_SYNTAX_ERROR;
        if (key == "delay") {
            if (Error error = parseDouble(value.delay))
                return error;
        } else if (key == "easing") {
            if (Error error = parseNonstdOptionalStdVectorDouble(value.easing))
                return error;
        } else if (key == "transform") {
            if (Error error = parseNonstdOptionalStdArrayDouble6(value.transform))
                return error;
        } else if (key == "rotation") {
            if (Error error = parseNonstdOptionalDouble(value.rotation))
                return error;
        } else if (key == "opacity") {
            if (Error error = parseNonstdOptionalDouble(value.opacity))
                return error;
        } else if (key == "color") {
            if (Error error = parseNonstdOptionalOctopusColor(value.color))
                return error;
        } else {
            if (Error error = skipValue())
                return error;
        }
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseStdVectorOdeLayerAnimationKeyframe(std::vector<ode::LayerAnimation::Keyframe> &value) {
    if (!matchSymbol('['))
        return ErrorType::TYPE_MISMATCH;
    value.clear();
    int separatorCheck = -1;
    while (!matchSymbol(']')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseOdeLayerAnimationKeyframe((value.emplace_back(), value.back())))
            return error;
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseStdArrayDouble2(std::array<double, 2> &value) {
    if (!matchSymbol('['))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    int i = 0;
    while (!matchSymbol(']')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (i == 2)
            return ErrorType::ARRAY_SIZE_MISMATCH;
        if (ErrorType error = parseDouble(value[i]))
            return error;
        ++i;
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    if (i != 2)
        return ErrorType::ARRAY_SIZE_MISMATCH;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseNonstdOptionalStdArrayDouble2(nonstd::optional<std::array<double, 2> > &value) {
    skipWhitespace();
    if (cur[0] == 'n' && cur[1] == 'u' && cur[2] == 'l' && cur[3] == 'l' && !isAlphanumeric(cur[4]) && cur[4] != '_' && ((cur += 4), true))
        value.reset();
    else if (Error error = parseStdArrayDouble2((value = std::array<double, 2>()).value()))
        return error;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseOdeLayerAnimation(ode::LayerAnimation &value) {
    std::string key;
    if (!matchSymbol('{'))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    while (!matchSymbol('}')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseStdString(key))
            return error;
        if (!matchSymbol(':'))
            return ErrorType::JSON_SYNTAX_ERROR;
        if (key == "layer") {
            if (Error error = parseStdString(value.layer))
                return error;
        } else if (key == "type") {
            if (Error error = parseOdeLayerAnimationType(value.type))
                return error;
        } else if (key == "keyframes") {
            if (Error error = parseStdVectorOdeLayerAnimationKeyframe(value.keyframes))
                return error;
        } else if (key == "rotationCenter") {
            if (Error error = parseNonstdOptionalStdArrayDouble2(value.rotationCenter))
                return error;
        } else {
            if (Error error = skipValue())
                return error;
        }
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseStdVectorOdeLayerAnimation(std::vector<ode::LayerAnimation> &value) {
    if (!matchSymbol('['))
        return ErrorType::TYPE_MISMATCH;
    value.clear();
    int separatorCheck = -1;
    while (!matchSymbol(']')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseOdeLayerAnimation((value.emplace_back(), value.back())))
            return error;
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

AnimationParser::ErrorType AnimationParser::parseOdeDocumentAnimation(ode::DocumentAnimation &value) {
    std::string key;
    if (!matchSymbol('{'))
        return ErrorType::TYPE_MISMATCH;
    int separatorCheck = -1;
    while (!matchSymbol('}')) {
        if (!separatorCheck)
            return ErrorType::JSON_SYNTAX_ERROR;
        if (ErrorType error = parseStdString(key))
            return error;
        if (!matchSymbol(':'))
            return ErrorType::JSON_SYNTAX_ERROR;
        if (key == "animations") {
            if (Error error = parseStdVectorOdeLayerAnimation(value.animations))
                return error;
        } else {
            if (Error error = skipValue())
                return error;
        }
        separatorCheck = matchSymbol(',');
    }
    if (separatorCheck == 1)
        return ErrorType::JSON_SYNTAX_ERROR;
    return ErrorType::OK;
}

}
