name: npm publish

inputs:
  directory:
    description: Path to package to be published
    required: true
  npm_token:
    description: npm token to be used for publishing
    required: true

runs:
  using: "composite"
  steps:
    - id: script
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      run: |
        set -xe
        if [ -z "$ODE_NPM_VERSION" ]; then
          echo "Missing env: ODE_NPM_VERSION. Did you run determine-version?"
          exit 1
        fi
        cd ${{ inputs.directory }}
        pkg_name=`jq .name package.json -r`
        json_exist=`npm -s view $pkg_name@$ODE_NPM_VERSION || true 2> /dev/null`
        if ! [ -z "$json_exist" ]; then
          echo "Package $pkg_name with version $ODE_NPM_VERSION is already published. Skipping."
          exit 0
        fi
        pkg_json_version=`jq .version package.json -r`
        if [ "$ODE_NPM_VERSION" != "$pkg_json_version" ]; then
          echo "Error: Versions do not match"
          exit 1
        fi
        tag=alpha
        if ${{ github.ref_type == 'tag' }}; then tag=latest; fi
        echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
        npm publish --tag $tag .
