
// FILE GENERATED BY generate-api-bindings.py
#pragma once
#include <napi.h>
#include <ode/logic-api.h>

std::string LayerType_to_string(ODE_LayerType value);
std::string ParseError_Type_to_string(ODE_ParseError::Type value);
