
// FILE GENERATED BY generate-api-bindings.py
#pragma once
#include <napi.h>
#include <ode/logic-api.h>

std::string ode_napi_enum_to_string(ODE_LayerType value);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_LayerType& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_Transformation& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_EngineAttributes& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_ComponentMetadata& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_LayerList::Entry& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_LayerList& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_LayerMetrics& source);
std::string ode_napi_enum_to_string(ODE_ParseError::Type value);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_ParseError::Type& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_ParseError& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_EngineHandle& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_DesignHandle& source);
Napi::Value ode_napi_serialize(Napi::Env env, const ODE_ComponentHandle& source);
