name: Determine npm version

runs:
  using: "composite"
  steps:
    - id: script
      shell: bash
      run: |
        set -xe
        BASE_VERSION=`jq .version vcpkg.json -r`
        if [ $GITHUB_REF_TYPE == tag ]; then
          if [ "v$BASE_VERSION" == "${{ github.ref_name }}" ]; then
            echo "ODE_NPM_VERSION=$BASE_VERSION" >> $GITHUB_ENV
          else
            echo "ODE_NPM_VERSION=$BASE_VERSION-${{ github.ref_name }}" >> $GITHUB_ENV
          fi
        else
          echo "ODE_NPM_VERSION=$BASE_VERSION-`git show -s --format=%h/%cs | tr -d - | tr / -`" >> $GITHUB_ENV
        fi
