name: build

on:
  push

env:
  GITLAB_REGISTRY: registry.avcd.cz
  GITLAB_PROJECT: opendesign/open-design-engine
  GITLAB_USERNAME: registry

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Gitlab Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITLAB_REGISTRY }}
          username: ${{ env.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
      - name: Extract job Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITLAB_REGISTRY }}/${{ env.GITLAB_PROJECT }}
          tags: |
            # Add default tags based on job trigger
            type=ref,event=branch
            type=ref,event=pr
            # Set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Dynamically set the branch name as a prefix, will result in $BRANCH-$SHA tags
            type=sha,prefix={{branch}}-
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./dockerfiles/debian-build/Dockerfile
          build-args: |
            ODE_BUILD_COMMIT="${{ github.sha }}"
      - name: Adding output tags to summary
        run: echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY