name: Repository lint check
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Run repo-check.py
       run: |
         python repo-check.py "${{ github.event.head_commit.message }}"
