name: Mac OS build
on: [push]

jobs:
  macos:
    runs-on: macos-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx-release

    steps:
      - uses: actions/checkout@v3
        with:
          # Personal token with read-only access to liboctopus and open-design-text-renderer
          # https://github.com/organizations/opendesigndev/settings/personal-access-tokens/39049
          token: ${{ secrets.ODE_REPOS_TOKEN }}
          submodules: true

      - name: Install prerequisites
        run: brew install automake autoconf autoconf-archive

      - name: Get project variables
        run: |
          printf "VCPKG_BASELINE=%s\n" $(jq -r '."builtin-baseline"' vcpkg.json) >> $GITHUB_ENV;

      - name: Setup vcpkg dependencies (cached)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgJsonGlob: vcpkg.json
          vcpkgGitCommitId: ${{ env.VCPKG_BASELINE }}

      - name: Configure and build ODE
        uses: lukka/run-cmake@v10
        with:
          configurePreset: osx-rel
          buildPreset: osx-rel
