name: MacOS Build
on: [push]

jobs:
  mac_build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Personal token with read-only access to liboctopus and open-design-text-renderer
          # https://github.com/organizations/opendesigndev/settings/personal-access-tokens/39049
          token: ${{ secrets.ODE_REPOS_TOKEN }}
          submodules: true

      - name: Install prerequisites
        run: brew install automake autoconf autoconf-archive

      - name: Setup vcpkg dependencies (cached)
        uses: lukka/run-vcpkg@v10

      - name: Configure and build ODE
        uses: lukka/run-cmake@v10
        with:
          configurePreset: osx-rel
          buildPreset: osx-rel

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx-release
