name: MacOS Build
on: [push]

jobs:
  mac_build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Personal token with read-only access to liboctopus and open-design-text-renderer
          # https://github.com/organizations/opendesigndev/settings/personal-access-tokens/39049
          token: ${{ secrets.ODE_REPOS_TOKEN }}
          submodules: true

      - name: Install prerequisites
        run: brew install automake autoconf autoconf-archive

      - name: Configure engine build
        run: VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT cmake -S . -B build

      - name: Build engine
        run: cmake --build build
