name: Mac OS build
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - review_requested
      - ready_for_review
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  macos:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false) || github.event_name == 'push'
    runs-on: macos-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx-release

    steps:
      - uses: actions/checkout@v3
        with:
          # Personal token with read-only access to liboctopus and open-design-text-renderer
          # https://github.com/organizations/opendesigndev/settings/personal-access-tokens/39049
          token: ${{ secrets.ODE_REPOS_TOKEN }}
          submodules: true

      - name: Install prerequisites
        run: brew install automake autoconf autoconf-archive

      - name: Get project variables
        run: |
          printf "VCPKG_BASELINE=%s\n" $(jq -r '."builtin-baseline"' vcpkg.json) >> $GITHUB_ENV;

      - name: Setup vcpkg dependencies (cached)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgJsonGlob: vcpkg.json
          vcpkgGitCommitId: ${{ env.VCPKG_BASELINE }}

      - name: Configure and build ODE
        uses: lukka/run-cmake@v10
        with:
          configurePreset: osx-rel
          buildPreset: osx-rel

      - name: Gather artifacts
        run: |
          mkdir -p build/artifacts/open-design-engine
          cp build/osx-rel/ode-logic/ode-logic-cli build/artifacts/open-design-engine
          cp build/osx-rel/ode-renderer/ode-renderer-cli build/artifacts/open-design-engine
          cp build/osx-rel/ode-animation-prototype/ode-animation-prototype-window build/artifacts/open-design-engine
          cp build/osx-rel/tests/renderer-unit-tests/renderer-unit-tests build/artifacts/open-design-engine
          cp build/osx-rel/tools/render-graph-inspector/render-graph-inspector build/artifacts/open-design-engine

      - name: Upload arifacts
        uses: actions/upload-artifact@v3
        with:
          name: ode-osx64
          path: build/artifacts
