name: wasm
on:
  push

env:
  GITLAB_REGISTRY: registry.avcd.cz
  GITLAB_PROJECT: opendesign/open-design-engine/wasm
  GITLAB_USERNAME: registry

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Personal token with read-only access to liboctopus and open-design-text-renderer
          # https://github.com/organizations/opendesigndev/settings/personal-access-tokens/39049
          token: ${{ secrets.ODE_REPOS_TOKEN }}
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Gitlab Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITLAB_REGISTRY }}
          username: ${{ env.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
      - name: Extract job Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITLAB_REGISTRY }}/${{ env.GITLAB_PROJECT }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ode-animation-prototype/docker/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Adding output tags to summary
        run: |
          echo "Main docker image: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}" >> $GITHUB_STEP_SUMMARY
      - name: Build WASM and publish
        run: docker run -v $(pwd):/src -e NPM_TOKEN=$NPM_TOKEN $BASE_IMAGE_CACHE bash ode-animation-prototype/wasm-build.sh --publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          BASE_IMAGE_CACHE: "${{ fromJSON(steps.meta.outputs.json).tags[1] }}"
      - name: WASM artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: |
            build/wasm-release/ode-animation-prototype
