name: Windows build
on:
  pull_request:
    types:
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  windows:
    if: |
      ((github.event_name == 'pull_request' && github.event.pull_request.draft == false) || github.event_name == 'push')
      && !contains(github.event.pull_request.labels.*.name, 'ci:minimal')
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get project variables
        run: |
          "VCPKG_BASELINE="+(Get-Content vcpkg.json | Out-String | ConvertFrom-Json)."builtin-baseline" >> $env:GITHUB_ENV

      - name: Setup vcpkg dependencies (cached)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgJsonGlob: vcpkg.json
          vcpkgGitCommitId: ${{ env.VCPKG_BASELINE }}

      - name: Configure and build ODE
        uses: lukka/run-cmake@v10
        with:
          configurePreset: win64-github-actions
          buildPreset: win64-github-actions

      - name: Gather artifacts
        run: |
          New-Item -ItemType Directory -Force -Path build/artifacts/open-design-engine
          Copy-Item build/win64/ode-logic/Release/ode-logic-cli.exe -Destination build/artifacts/open-design-engine
          Copy-Item build/win64/ode-renderer/Release/ode-renderer-cli.exe -Destination build/artifacts/open-design-engine
          Copy-Item build/win64/tests/renderer-output-tests/Release/renderer-output-tests.exe -Destination build/artifacts/open-design-engine
          Copy-Item build/win64/tools/animation-prototype/Release/animation-prototype-window.exe -Destination build/artifacts/open-design-engine
          Copy-Item build/win64/tools/render-graph-inspector/Release/render-graph-inspector.exe -Destination build/artifacts/open-design-engine

      - name: Upload arifacts
        uses: actions/upload-artifact@v3
        with:
          name: ode-win64
          path: build/artifacts
